{
 "title": "Air Purifier - Lecture room",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AQI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "target": "esp_environment.labsensors-air_purifier_lecture_room.aqi"
    }
   ]
  },
  {
   "title": "Average AQI",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "target": "esp_environment.labsensors-air_purifier_lecture_room.aqi-average"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "esp_environment.labsensors-air_purifier_lecture_room.temperature"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "target": "esp_environment.labsensors-air_purifier_lecture_room.humidity"
    }
   ]
  },
  {
   "title": "State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "powered" }
   ],
   "targets": [
    {
     "target": "esp_environment.labsensors-air_purifier_lecture_room.state"
    }
   ]
  }
 ]
}